package com.example.demo.models;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.web.socket.WebSocketSession;

import java.time.LocalDateTime;

/**
 * Represents a participant in a video conference room
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Participant {

    /**
     * Unique participant ID (UUID generated by frontend)
     */
    private String userId;

    /**
     * Display name (anonymous or user-provided)
     */
    private String name;

    /**
     * WebSocket session for this participant
     */
    private WebSocketSession session;

    /**
     * Room ID this participant belongs to
     */
    private String roomId;

    /**
     * When the participant joined
     */
    private LocalDateTime joinedAt;

    /**
     * Media state
     */
    private boolean audioEnabled;
    private boolean videoEnabled;

    /**
     * Check if the WebSocket session is still active
     */
    public boolean isConnected() {
        return session != null && session.isOpen();
    }
}
